# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 360)
        MainWindow.setMaximumSize(QtCore.QSize(640, 360))
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gvThumbnail = QtWidgets.QGraphicsView(self.centralwidget)
        self.gvThumbnail.setEnabled(False)
        self.gvThumbnail.setGeometry(QtCore.QRect(330, 40, 291, 171))
        self.gvThumbnail.setObjectName("gvThumbnail")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 0, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(False)
        self.progressBar.setGeometry(QtCore.QRect(170, 270, 451, 41))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.psbDowload = QtWidgets.QPushButton(self.centralwidget)
        self.psbDowload.setEnabled(False)
        self.psbDowload.setGeometry(QtCore.QRect(20, 270, 141, 41))
        self.psbDowload.setObjectName("psbDowload")
        self.txtURL = QtWidgets.QTextEdit(self.centralwidget)
        self.txtURL.setGeometry(QtCore.QRect(10, 190, 211, 31))
        self.txtURL.setObjectName("txtURL")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 160, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.cbxResolutions = QtWidgets.QComboBox(self.centralwidget)
        self.cbxResolutions.setEnabled(False)
        self.cbxResolutions.setGeometry(QtCore.QRect(110, 230, 211, 31))
        self.cbxResolutions.setObjectName("cbxResolutions")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 230, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.psbCheck = QtWidgets.QPushButton(self.centralwidget)
        self.psbCheck.setGeometry(QtCore.QRect(230, 190, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.psbCheck.setFont(font)
        self.psbCheck.setObjectName("psbCheck")
        self.lblName = QtWidgets.QLabel(self.centralwidget)
        self.lblName.setGeometry(QtCore.QRect(430, 220, 81, 21))
        self.lblName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblName.setObjectName("lblName")
        self.lblViews = QtWidgets.QLabel(self.centralwidget)
        self.lblViews.setGeometry(QtCore.QRect(330, 250, 131, 16))
        self.lblViews.setObjectName("lblViews")
        self.lblDuration = QtWidgets.QLabel(self.centralwidget)
        self.lblDuration.setGeometry(QtCore.QRect(516, 243, 101, 20))
        self.lblDuration.setObjectName("lblDuration")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PyTube Downloader"))
        self.psbDowload.setText(_translate("MainWindow", "Download"))
        self.label_2.setText(_translate("MainWindow", "Video URL"))
        self.label_3.setText(_translate("MainWindow", "Resolution:"))
        self.psbCheck.setText(_translate("MainWindow", "Check"))
        self.lblName.setText(_translate("MainWindow", "Title"))
        self.lblViews.setText(_translate("MainWindow", "Views: "))
        self.lblDuration.setText(_translate("MainWindow", "Duration: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
